# Build Stage
FROM golang:1.21-alpine AS builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod ./
# COPY go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o link-service ./cmd/server

# Production Stage
FROM gcr.io/distroless/static-debian12

WORKDIR /app

COPY --from=builder /app/link-service .

EXPOSE 8080

CMD ["./link-service"]